//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCLogin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        public int UserID { get; set; }
        [DisplayName("Felhasználónév:")]
        [Required(ErrorMessage = "A mezõ kitöltése kötelezõ.")]
        public string UserName { get; set; }
        [DisplayName("Jelszó:")]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "A mezõ kitöltése kötelezõ")]
        public string Password { get; set; }
        public string LoginErrorMessage { get; set; }
    }
}
